First module
multiversx/mx-multisig-and-modules pull request #2
Opened 2024-08-09 11:26 UTC by dorin-iancu

2024-08-13 07:58 UTC, CostinCarabas approved these changes

2024-08-13 07:58 UTC, CostinCarabas commented on common-modules/multisig-interactions/src/lib.rs
> +    fn enable_interaction(&self, sc_address: ManagedAddress, endpoint_name: ManagedBuffer) {
`enable` and `disable` could be performed in a single function.

2024-08-13 08:45 UTC, dorin-iancu commented on common-modules/multisig-interactions/src/lib.rs
> +    fn enable_interaction(&self, sc_address: ManagedAddress, endpoint_name: ManagedBuffer) {
Those were the specs :)

2024-08-14 12:06 UTC, ccorcoveanu requested changes

2024-08-14 12:06 UTC, ccorcoveanu commented on common-modules/multisig-interactions/src/views.rs
> +    fn can_execute(
This should be in the actual module contract folder, as this is the defining logic of it

2024-08-14 12:06 UTC, ccorcoveanu commented on common-modules/only-by-multisig/src/lib.rs
> +pub trait OnlyByMultisig {
I think we can call it OnlyMultisig, without `by` - the same patterns is used in ethereum access control implementations and I also think it sounds a bit better

2024-08-14 12:06 UTC, ccorcoveanu commented on multisig-improved/src/action_types/propose.rs
> +    fn propose_action_no_checks(&self, action: &Action<Self::Api>) -> ActionId {
we can call this `add_action` since it's kind of all it does?

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/main.rs
> +        opt_allowed_token_id: Option<EgldOrEsdtTokenIdentifier>,
Should we have a list of payments as it is passed from can_execute and check for inclusion?

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/main.rs
> +    #[endpoint(addAllowedAddresses)]
I think we can add also a remove function for allowed addresses.

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/storage.rs
> +    #[storage_mapper("tok")]
I think we can use full name, I don't really see a win for 2 character win on the storage name

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/views.rs
> +        } else {
I don't think we need this. If the front ends already know that an empty list means "any", than it should also know on the view function to display it correctly

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/views.rs
> +        } else {
Or better, let's define a constant for an "any" address. Even if it's the zero address. Then we can also have a view function to get it and display it in the front-end. When checking for allowed access, if we encounter it we return true. This way we still remove the `else` we have here

2024-08-14 12:06 UTC, ccorcoveanu commented on passthrough/tests/pass_test.rs
> +#[should_panic(expected = "only board members and proposers can propose")]
Is this the only way we can catch the panic now? I don't like this approach since `propose_add_interaction` can panic with the same message. So we are not guaranteed that if the test passes it passes from the correct assumptions. Can we catch this panic only in the `propose_transfer_execute` call?

2024-08-14 12:07 UTC, ccorcoveanu commented on common-modules/multisig-interactions/src/lib.rs
> +    fn enable_interaction(&self, sc_address: ManagedAddress, endpoint_name: ManagedBuffer) {
Where possible I like this approach from a single (maybe stupid) reason. You can easily see (and filter) what action was performed from the explorer in the transaction list - and you don't need to go into the details and check the arguments.

2024-08-14 13:23 UTC, dorin-iancu commented on common-modules/multisig-interactions/src/views.rs
> +    fn can_execute(
I've already moved everything in the contract folder. I believe that's what you meant?

2024-08-14 13:26 UTC, dorin-iancu commented on passthrough/src/multisig_interactions/main.rs
> +        opt_allowed_token_id: Option<EgldOrEsdtTokenIdentifier>,
So you'd want this to be a list instead?

2024-08-14 13:29 UTC, dorin-iancu commented on passthrough/src/multisig_interactions/storage.rs
> +    #[storage_mapper("tok")]
I try to keep all storage keys under 32 bytes, makes it cheaper.

2024-08-14 13:34 UTC, dorin-iancu commented on passthrough/tests/pass_test.rs
> +#[should_panic(expected = "only board members and proposers can propose")]
Nope. But you already know the code works until then from the test above, so the error has to come from further down.

2024-08-14 13:36 UTC, dorin-iancu commented on passthrough/src/multisig_interactions/views.rs
> +        } else {
Nah, that complicates the code too much. I've simply removed it for now.

2024-08-14 13:38 UTC, dorin-iancu commented on passthrough/src/multisig_interactions/main.rs
> +        opt_allowed_token_id: Option<EgldOrEsdtTokenIdentifier>,
Not sure I'd complicate the contract with something like that. Unlikely you'd need more than 1 token, since this is supposed to only be used for simple actions.

2024-08-14 13:58 UTC, ccorcoveanu commented on common-modules/multisig-interactions/src/views.rs
> +    fn can_execute(
yes, saw that, and also removed some of the comments related with that, but this one seems to have escaped into the review

2024-08-14 13:58 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/main.rs
> +        opt_allowed_token_id: Option<EgldOrEsdtTokenIdentifier>,
ok, we'll revise if we find a use case for it

2024-08-14 14:01 UTC, ccorcoveanu commented on passthrough/tests/pass_test.rs
> +#[should_panic(expected = "only board members and proposers can propose")]
Tests should be independent (removing one test should not affect assumptions about others), if we can do it, let's do it please

2024-08-14 14:06 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/storage.rs
> +    #[storage_mapper("tok")]
yeah but doing it only here is not a uniform approach. also, "token" is nowhere near 32 bytes, let's use the whole word please as not to refactor all the mappers

2024-08-14 14:07 UTC, ccorcoveanu commented on passthrough/src/multisig_interactions/views.rs
> +        } else {
I'm ok with this version also 👍

2024-08-16 06:40 UTC, merged